// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: cheqd/oracle/v2/oracle.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { DecCoin } from "../../../cosmos/base/v1beta1/coin.js";
function createBaseParams() {
    return {
        votePeriod: 0n,
        voteThreshold: "",
        rewardBands: [],
        rewardDistributionWindow: 0n,
        acceptList: [],
        slashFraction: "",
        slashWindow: 0n,
        minValidPerWindow: "",
        mandatoryList: [],
        historicStampPeriod: 0n,
        medianStampPeriod: 0n,
        maximumPriceStamps: 0n,
        maximumMedianStamps: 0n,
        currencyPairProviders: [],
        currencyDeviationThresholds: [],
        usdcIbcDenom: "",
        slashingEnabled: false,
        averagingWindow: 0n,
    };
}
export const Params = {
    encode(message, writer = new BinaryWriter()) {
        if (message.votePeriod !== 0n) {
            if (BigInt.asUintN(64, message.votePeriod) !== message.votePeriod) {
                throw new globalThis.Error("value provided for field message.votePeriod of type uint64 too large");
            }
            writer.uint32(8).uint64(message.votePeriod);
        }
        if (message.voteThreshold !== "") {
            writer.uint32(18).string(message.voteThreshold);
        }
        for (const v of message.rewardBands) {
            RewardBand.encode(v, writer.uint32(26).fork()).join();
        }
        if (message.rewardDistributionWindow !== 0n) {
            if (BigInt.asUintN(64, message.rewardDistributionWindow) !== message.rewardDistributionWindow) {
                throw new globalThis.Error("value provided for field message.rewardDistributionWindow of type uint64 too large");
            }
            writer.uint32(32).uint64(message.rewardDistributionWindow);
        }
        for (const v of message.acceptList) {
            Denom.encode(v, writer.uint32(42).fork()).join();
        }
        if (message.slashFraction !== "") {
            writer.uint32(50).string(message.slashFraction);
        }
        if (message.slashWindow !== 0n) {
            if (BigInt.asUintN(64, message.slashWindow) !== message.slashWindow) {
                throw new globalThis.Error("value provided for field message.slashWindow of type uint64 too large");
            }
            writer.uint32(56).uint64(message.slashWindow);
        }
        if (message.minValidPerWindow !== "") {
            writer.uint32(66).string(message.minValidPerWindow);
        }
        for (const v of message.mandatoryList) {
            Denom.encode(v, writer.uint32(74).fork()).join();
        }
        if (message.historicStampPeriod !== 0n) {
            if (BigInt.asUintN(64, message.historicStampPeriod) !== message.historicStampPeriod) {
                throw new globalThis.Error("value provided for field message.historicStampPeriod of type uint64 too large");
            }
            writer.uint32(80).uint64(message.historicStampPeriod);
        }
        if (message.medianStampPeriod !== 0n) {
            if (BigInt.asUintN(64, message.medianStampPeriod) !== message.medianStampPeriod) {
                throw new globalThis.Error("value provided for field message.medianStampPeriod of type uint64 too large");
            }
            writer.uint32(88).uint64(message.medianStampPeriod);
        }
        if (message.maximumPriceStamps !== 0n) {
            if (BigInt.asUintN(64, message.maximumPriceStamps) !== message.maximumPriceStamps) {
                throw new globalThis.Error("value provided for field message.maximumPriceStamps of type uint64 too large");
            }
            writer.uint32(96).uint64(message.maximumPriceStamps);
        }
        if (message.maximumMedianStamps !== 0n) {
            if (BigInt.asUintN(64, message.maximumMedianStamps) !== message.maximumMedianStamps) {
                throw new globalThis.Error("value provided for field message.maximumMedianStamps of type uint64 too large");
            }
            writer.uint32(104).uint64(message.maximumMedianStamps);
        }
        for (const v of message.currencyPairProviders) {
            CurrencyPairProviders.encode(v, writer.uint32(114).fork()).join();
        }
        for (const v of message.currencyDeviationThresholds) {
            CurrencyDeviationThreshold.encode(v, writer.uint32(122).fork()).join();
        }
        if (message.usdcIbcDenom !== "") {
            writer.uint32(130).string(message.usdcIbcDenom);
        }
        if (message.slashingEnabled !== false) {
            writer.uint32(136).bool(message.slashingEnabled);
        }
        if (message.averagingWindow !== 0n) {
            if (BigInt.asUintN(64, message.averagingWindow) !== message.averagingWindow) {
                throw new globalThis.Error("value provided for field message.averagingWindow of type uint64 too large");
            }
            writer.uint32(144).uint64(message.averagingWindow);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseParams();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.votePeriod = reader.uint64();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.voteThreshold = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.rewardBands.push(RewardBand.decode(reader, reader.uint32()));
                    continue;
                }
                case 4: {
                    if (tag !== 32) {
                        break;
                    }
                    message.rewardDistributionWindow = reader.uint64();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.acceptList.push(Denom.decode(reader, reader.uint32()));
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.slashFraction = reader.string();
                    continue;
                }
                case 7: {
                    if (tag !== 56) {
                        break;
                    }
                    message.slashWindow = reader.uint64();
                    continue;
                }
                case 8: {
                    if (tag !== 66) {
                        break;
                    }
                    message.minValidPerWindow = reader.string();
                    continue;
                }
                case 9: {
                    if (tag !== 74) {
                        break;
                    }
                    message.mandatoryList.push(Denom.decode(reader, reader.uint32()));
                    continue;
                }
                case 10: {
                    if (tag !== 80) {
                        break;
                    }
                    message.historicStampPeriod = reader.uint64();
                    continue;
                }
                case 11: {
                    if (tag !== 88) {
                        break;
                    }
                    message.medianStampPeriod = reader.uint64();
                    continue;
                }
                case 12: {
                    if (tag !== 96) {
                        break;
                    }
                    message.maximumPriceStamps = reader.uint64();
                    continue;
                }
                case 13: {
                    if (tag !== 104) {
                        break;
                    }
                    message.maximumMedianStamps = reader.uint64();
                    continue;
                }
                case 14: {
                    if (tag !== 114) {
                        break;
                    }
                    message.currencyPairProviders.push(CurrencyPairProviders.decode(reader, reader.uint32()));
                    continue;
                }
                case 15: {
                    if (tag !== 122) {
                        break;
                    }
                    message.currencyDeviationThresholds.push(CurrencyDeviationThreshold.decode(reader, reader.uint32()));
                    continue;
                }
                case 16: {
                    if (tag !== 130) {
                        break;
                    }
                    message.usdcIbcDenom = reader.string();
                    continue;
                }
                case 17: {
                    if (tag !== 136) {
                        break;
                    }
                    message.slashingEnabled = reader.bool();
                    continue;
                }
                case 18: {
                    if (tag !== 144) {
                        break;
                    }
                    message.averagingWindow = reader.uint64();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            votePeriod: isSet(object.votePeriod) ? BigInt(object.votePeriod) : 0n,
            voteThreshold: isSet(object.voteThreshold) ? globalThis.String(object.voteThreshold) : "",
            rewardBands: globalThis.Array.isArray(object?.rewardBands)
                ? object.rewardBands.map((e) => RewardBand.fromJSON(e))
                : [],
            rewardDistributionWindow: isSet(object.rewardDistributionWindow) ? BigInt(object.rewardDistributionWindow) : 0n,
            acceptList: globalThis.Array.isArray(object?.acceptList)
                ? object.acceptList.map((e) => Denom.fromJSON(e))
                : [],
            slashFraction: isSet(object.slashFraction) ? globalThis.String(object.slashFraction) : "",
            slashWindow: isSet(object.slashWindow) ? BigInt(object.slashWindow) : 0n,
            minValidPerWindow: isSet(object.minValidPerWindow) ? globalThis.String(object.minValidPerWindow) : "",
            mandatoryList: globalThis.Array.isArray(object?.mandatoryList)
                ? object.mandatoryList.map((e) => Denom.fromJSON(e))
                : [],
            historicStampPeriod: isSet(object.historicStampPeriod) ? BigInt(object.historicStampPeriod) : 0n,
            medianStampPeriod: isSet(object.medianStampPeriod) ? BigInt(object.medianStampPeriod) : 0n,
            maximumPriceStamps: isSet(object.maximumPriceStamps) ? BigInt(object.maximumPriceStamps) : 0n,
            maximumMedianStamps: isSet(object.maximumMedianStamps) ? BigInt(object.maximumMedianStamps) : 0n,
            currencyPairProviders: globalThis.Array.isArray(object?.currencyPairProviders)
                ? object.currencyPairProviders.map((e) => CurrencyPairProviders.fromJSON(e))
                : [],
            currencyDeviationThresholds: globalThis.Array.isArray(object?.currencyDeviationThresholds)
                ? object.currencyDeviationThresholds.map((e) => CurrencyDeviationThreshold.fromJSON(e))
                : [],
            usdcIbcDenom: isSet(object.usdcIbcDenom) ? globalThis.String(object.usdcIbcDenom) : "",
            slashingEnabled: isSet(object.slashingEnabled) ? globalThis.Boolean(object.slashingEnabled) : false,
            averagingWindow: isSet(object.averagingWindow) ? BigInt(object.averagingWindow) : 0n,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.votePeriod !== 0n) {
            obj.votePeriod = message.votePeriod.toString();
        }
        if (message.voteThreshold !== "") {
            obj.voteThreshold = message.voteThreshold;
        }
        if (message.rewardBands?.length) {
            obj.rewardBands = message.rewardBands.map((e) => RewardBand.toJSON(e));
        }
        if (message.rewardDistributionWindow !== 0n) {
            obj.rewardDistributionWindow = message.rewardDistributionWindow.toString();
        }
        if (message.acceptList?.length) {
            obj.acceptList = message.acceptList.map((e) => Denom.toJSON(e));
        }
        if (message.slashFraction !== "") {
            obj.slashFraction = message.slashFraction;
        }
        if (message.slashWindow !== 0n) {
            obj.slashWindow = message.slashWindow.toString();
        }
        if (message.minValidPerWindow !== "") {
            obj.minValidPerWindow = message.minValidPerWindow;
        }
        if (message.mandatoryList?.length) {
            obj.mandatoryList = message.mandatoryList.map((e) => Denom.toJSON(e));
        }
        if (message.historicStampPeriod !== 0n) {
            obj.historicStampPeriod = message.historicStampPeriod.toString();
        }
        if (message.medianStampPeriod !== 0n) {
            obj.medianStampPeriod = message.medianStampPeriod.toString();
        }
        if (message.maximumPriceStamps !== 0n) {
            obj.maximumPriceStamps = message.maximumPriceStamps.toString();
        }
        if (message.maximumMedianStamps !== 0n) {
            obj.maximumMedianStamps = message.maximumMedianStamps.toString();
        }
        if (message.currencyPairProviders?.length) {
            obj.currencyPairProviders = message.currencyPairProviders.map((e) => CurrencyPairProviders.toJSON(e));
        }
        if (message.currencyDeviationThresholds?.length) {
            obj.currencyDeviationThresholds = message.currencyDeviationThresholds.map((e) => CurrencyDeviationThreshold.toJSON(e));
        }
        if (message.usdcIbcDenom !== "") {
            obj.usdcIbcDenom = message.usdcIbcDenom;
        }
        if (message.slashingEnabled !== false) {
            obj.slashingEnabled = message.slashingEnabled;
        }
        if (message.averagingWindow !== 0n) {
            obj.averagingWindow = message.averagingWindow.toString();
        }
        return obj;
    },
    create(base) {
        return Params.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseParams();
        message.votePeriod = object.votePeriod ?? 0n;
        message.voteThreshold = object.voteThreshold ?? "";
        message.rewardBands = object.rewardBands?.map((e) => RewardBand.fromPartial(e)) || [];
        message.rewardDistributionWindow = object.rewardDistributionWindow ?? 0n;
        message.acceptList = object.acceptList?.map((e) => Denom.fromPartial(e)) || [];
        message.slashFraction = object.slashFraction ?? "";
        message.slashWindow = object.slashWindow ?? 0n;
        message.minValidPerWindow = object.minValidPerWindow ?? "";
        message.mandatoryList = object.mandatoryList?.map((e) => Denom.fromPartial(e)) || [];
        message.historicStampPeriod = object.historicStampPeriod ?? 0n;
        message.medianStampPeriod = object.medianStampPeriod ?? 0n;
        message.maximumPriceStamps = object.maximumPriceStamps ?? 0n;
        message.maximumMedianStamps = object.maximumMedianStamps ?? 0n;
        message.currencyPairProviders = object.currencyPairProviders?.map((e) => CurrencyPairProviders.fromPartial(e)) ||
            [];
        message.currencyDeviationThresholds =
            object.currencyDeviationThresholds?.map((e) => CurrencyDeviationThreshold.fromPartial(e)) || [];
        message.usdcIbcDenom = object.usdcIbcDenom ?? "";
        message.slashingEnabled = object.slashingEnabled ?? false;
        message.averagingWindow = object.averagingWindow ?? 0n;
        return message;
    },
};
function createBaseDenom() {
    return { baseDenom: "", symbolDenom: "", exponent: 0 };
}
export const Denom = {
    encode(message, writer = new BinaryWriter()) {
        if (message.baseDenom !== "") {
            writer.uint32(10).string(message.baseDenom);
        }
        if (message.symbolDenom !== "") {
            writer.uint32(18).string(message.symbolDenom);
        }
        if (message.exponent !== 0) {
            writer.uint32(24).uint32(message.exponent);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseDenom();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.baseDenom = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.symbolDenom = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.exponent = reader.uint32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            baseDenom: isSet(object.baseDenom) ? globalThis.String(object.baseDenom) : "",
            symbolDenom: isSet(object.symbolDenom) ? globalThis.String(object.symbolDenom) : "",
            exponent: isSet(object.exponent) ? globalThis.Number(object.exponent) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.baseDenom !== "") {
            obj.baseDenom = message.baseDenom;
        }
        if (message.symbolDenom !== "") {
            obj.symbolDenom = message.symbolDenom;
        }
        if (message.exponent !== 0) {
            obj.exponent = Math.round(message.exponent);
        }
        return obj;
    },
    create(base) {
        return Denom.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseDenom();
        message.baseDenom = object.baseDenom ?? "";
        message.symbolDenom = object.symbolDenom ?? "";
        message.exponent = object.exponent ?? 0;
        return message;
    },
};
function createBaseRewardBand() {
    return { symbolDenom: "", rewardBand: "" };
}
export const RewardBand = {
    encode(message, writer = new BinaryWriter()) {
        if (message.symbolDenom !== "") {
            writer.uint32(10).string(message.symbolDenom);
        }
        if (message.rewardBand !== "") {
            writer.uint32(18).string(message.rewardBand);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRewardBand();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.symbolDenom = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.rewardBand = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            symbolDenom: isSet(object.symbolDenom) ? globalThis.String(object.symbolDenom) : "",
            rewardBand: isSet(object.rewardBand) ? globalThis.String(object.rewardBand) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.symbolDenom !== "") {
            obj.symbolDenom = message.symbolDenom;
        }
        if (message.rewardBand !== "") {
            obj.rewardBand = message.rewardBand;
        }
        return obj;
    },
    create(base) {
        return RewardBand.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRewardBand();
        message.symbolDenom = object.symbolDenom ?? "";
        message.rewardBand = object.rewardBand ?? "";
        return message;
    },
};
function createBaseAggregateExchangeRatePrevote() {
    return { hash: "", voter: "", submitBlock: 0n };
}
export const AggregateExchangeRatePrevote = {
    encode(message, writer = new BinaryWriter()) {
        if (message.hash !== "") {
            writer.uint32(10).string(message.hash);
        }
        if (message.voter !== "") {
            writer.uint32(18).string(message.voter);
        }
        if (message.submitBlock !== 0n) {
            if (BigInt.asUintN(64, message.submitBlock) !== message.submitBlock) {
                throw new globalThis.Error("value provided for field message.submitBlock of type uint64 too large");
            }
            writer.uint32(24).uint64(message.submitBlock);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAggregateExchangeRatePrevote();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.hash = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.voter = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.submitBlock = reader.uint64();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            hash: isSet(object.hash) ? globalThis.String(object.hash) : "",
            voter: isSet(object.voter) ? globalThis.String(object.voter) : "",
            submitBlock: isSet(object.submitBlock) ? BigInt(object.submitBlock) : 0n,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.hash !== "") {
            obj.hash = message.hash;
        }
        if (message.voter !== "") {
            obj.voter = message.voter;
        }
        if (message.submitBlock !== 0n) {
            obj.submitBlock = message.submitBlock.toString();
        }
        return obj;
    },
    create(base) {
        return AggregateExchangeRatePrevote.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseAggregateExchangeRatePrevote();
        message.hash = object.hash ?? "";
        message.voter = object.voter ?? "";
        message.submitBlock = object.submitBlock ?? 0n;
        return message;
    },
};
function createBaseAggregateExchangeRateVote() {
    return { exchangeRates: [], voter: "" };
}
export const AggregateExchangeRateVote = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.exchangeRates) {
            DecCoin.encode(v, writer.uint32(10).fork()).join();
        }
        if (message.voter !== "") {
            writer.uint32(18).string(message.voter);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAggregateExchangeRateVote();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.exchangeRates.push(DecCoin.decode(reader, reader.uint32()));
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.voter = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            exchangeRates: globalThis.Array.isArray(object?.exchangeRates)
                ? object.exchangeRates.map((e) => DecCoin.fromJSON(e))
                : [],
            voter: isSet(object.voter) ? globalThis.String(object.voter) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.exchangeRates?.length) {
            obj.exchangeRates = message.exchangeRates.map((e) => DecCoin.toJSON(e));
        }
        if (message.voter !== "") {
            obj.voter = message.voter;
        }
        return obj;
    },
    create(base) {
        return AggregateExchangeRateVote.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseAggregateExchangeRateVote();
        message.exchangeRates = object.exchangeRates?.map((e) => DecCoin.fromPartial(e)) || [];
        message.voter = object.voter ?? "";
        return message;
    },
};
function createBasePriceStamp() {
    return { exchangeRate: undefined, blockNum: 0n };
}
export const PriceStamp = {
    encode(message, writer = new BinaryWriter()) {
        if (message.exchangeRate !== undefined) {
            DecCoin.encode(message.exchangeRate, writer.uint32(10).fork()).join();
        }
        if (message.blockNum !== 0n) {
            if (BigInt.asUintN(64, message.blockNum) !== message.blockNum) {
                throw new globalThis.Error("value provided for field message.blockNum of type uint64 too large");
            }
            writer.uint32(16).uint64(message.blockNum);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePriceStamp();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.exchangeRate = DecCoin.decode(reader, reader.uint32());
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.blockNum = reader.uint64();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            exchangeRate: isSet(object.exchangeRate) ? DecCoin.fromJSON(object.exchangeRate) : undefined,
            blockNum: isSet(object.blockNum) ? BigInt(object.blockNum) : 0n,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.exchangeRate !== undefined) {
            obj.exchangeRate = DecCoin.toJSON(message.exchangeRate);
        }
        if (message.blockNum !== 0n) {
            obj.blockNum = message.blockNum.toString();
        }
        return obj;
    },
    create(base) {
        return PriceStamp.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePriceStamp();
        message.exchangeRate = (object.exchangeRate !== undefined && object.exchangeRate !== null)
            ? DecCoin.fromPartial(object.exchangeRate)
            : undefined;
        message.blockNum = object.blockNum ?? 0n;
        return message;
    },
};
function createBaseValidatorRewardSet() {
    return { validatorSet: [] };
}
export const ValidatorRewardSet = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.validatorSet) {
            writer.uint32(10).string(v);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseValidatorRewardSet();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.validatorSet.push(reader.string());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            validatorSet: globalThis.Array.isArray(object?.validatorSet)
                ? object.validatorSet.map((e) => globalThis.String(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.validatorSet?.length) {
            obj.validatorSet = message.validatorSet;
        }
        return obj;
    },
    create(base) {
        return ValidatorRewardSet.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseValidatorRewardSet();
        message.validatorSet = object.validatorSet?.map((e) => e) || [];
        return message;
    },
};
function createBaseCurrencyPairProviders() {
    return { baseDenom: "", quoteDenom: "", pairAddress: [], providers: [] };
}
export const CurrencyPairProviders = {
    encode(message, writer = new BinaryWriter()) {
        if (message.baseDenom !== "") {
            writer.uint32(10).string(message.baseDenom);
        }
        if (message.quoteDenom !== "") {
            writer.uint32(18).string(message.quoteDenom);
        }
        for (const v of message.pairAddress) {
            PairAddressProvider.encode(v, writer.uint32(26).fork()).join();
        }
        for (const v of message.providers) {
            writer.uint32(34).string(v);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCurrencyPairProviders();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.baseDenom = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.quoteDenom = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.pairAddress.push(PairAddressProvider.decode(reader, reader.uint32()));
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.providers.push(reader.string());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            baseDenom: isSet(object.baseDenom) ? globalThis.String(object.baseDenom) : "",
            quoteDenom: isSet(object.quoteDenom) ? globalThis.String(object.quoteDenom) : "",
            pairAddress: globalThis.Array.isArray(object?.pairAddress)
                ? object.pairAddress.map((e) => PairAddressProvider.fromJSON(e))
                : [],
            providers: globalThis.Array.isArray(object?.providers)
                ? object.providers.map((e) => globalThis.String(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.baseDenom !== "") {
            obj.baseDenom = message.baseDenom;
        }
        if (message.quoteDenom !== "") {
            obj.quoteDenom = message.quoteDenom;
        }
        if (message.pairAddress?.length) {
            obj.pairAddress = message.pairAddress.map((e) => PairAddressProvider.toJSON(e));
        }
        if (message.providers?.length) {
            obj.providers = message.providers;
        }
        return obj;
    },
    create(base) {
        return CurrencyPairProviders.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseCurrencyPairProviders();
        message.baseDenom = object.baseDenom ?? "";
        message.quoteDenom = object.quoteDenom ?? "";
        message.pairAddress = object.pairAddress?.map((e) => PairAddressProvider.fromPartial(e)) || [];
        message.providers = object.providers?.map((e) => e) || [];
        return message;
    },
};
function createBasePairAddressProvider() {
    return { address: "", addressProvider: "" };
}
export const PairAddressProvider = {
    encode(message, writer = new BinaryWriter()) {
        if (message.address !== "") {
            writer.uint32(10).string(message.address);
        }
        if (message.addressProvider !== "") {
            writer.uint32(18).string(message.addressProvider);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePairAddressProvider();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.address = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.addressProvider = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            address: isSet(object.address) ? globalThis.String(object.address) : "",
            addressProvider: isSet(object.addressProvider) ? globalThis.String(object.addressProvider) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.address !== "") {
            obj.address = message.address;
        }
        if (message.addressProvider !== "") {
            obj.addressProvider = message.addressProvider;
        }
        return obj;
    },
    create(base) {
        return PairAddressProvider.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePairAddressProvider();
        message.address = object.address ?? "";
        message.addressProvider = object.addressProvider ?? "";
        return message;
    },
};
function createBaseCurrencyDeviationThreshold() {
    return { baseDenom: "", threshold: "" };
}
export const CurrencyDeviationThreshold = {
    encode(message, writer = new BinaryWriter()) {
        if (message.baseDenom !== "") {
            writer.uint32(10).string(message.baseDenom);
        }
        if (message.threshold !== "") {
            writer.uint32(18).string(message.threshold);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCurrencyDeviationThreshold();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.baseDenom = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.threshold = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            baseDenom: isSet(object.baseDenom) ? globalThis.String(object.baseDenom) : "",
            threshold: isSet(object.threshold) ? globalThis.String(object.threshold) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.baseDenom !== "") {
            obj.baseDenom = message.baseDenom;
        }
        if (message.threshold !== "") {
            obj.threshold = message.threshold;
        }
        return obj;
    },
    create(base) {
        return CurrencyDeviationThreshold.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseCurrencyDeviationThreshold();
        message.baseDenom = object.baseDenom ?? "";
        message.threshold = object.threshold ?? "";
        return message;
    },
};
function createBaseParamUpdatePlan() {
    return { keys: [], height: 0n, changes: undefined };
}
export const ParamUpdatePlan = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.keys) {
            writer.uint32(10).string(v);
        }
        if (message.height !== 0n) {
            if (BigInt.asIntN(64, message.height) !== message.height) {
                throw new globalThis.Error("value provided for field message.height of type int64 too large");
            }
            writer.uint32(16).int64(message.height);
        }
        if (message.changes !== undefined) {
            Params.encode(message.changes, writer.uint32(26).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseParamUpdatePlan();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.keys.push(reader.string());
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.height = reader.int64();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.changes = Params.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            keys: globalThis.Array.isArray(object?.keys) ? object.keys.map((e) => globalThis.String(e)) : [],
            height: isSet(object.height) ? BigInt(object.height) : 0n,
            changes: isSet(object.changes) ? Params.fromJSON(object.changes) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.keys?.length) {
            obj.keys = message.keys;
        }
        if (message.height !== 0n) {
            obj.height = message.height.toString();
        }
        if (message.changes !== undefined) {
            obj.changes = Params.toJSON(message.changes);
        }
        return obj;
    },
    create(base) {
        return ParamUpdatePlan.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseParamUpdatePlan();
        message.keys = object.keys?.map((e) => e) || [];
        message.height = object.height ?? 0n;
        message.changes = (object.changes !== undefined && object.changes !== null)
            ? Params.fromPartial(object.changes)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=oracle.js.map