"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: cheqd/resource/v2/genesis.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.GenesisState = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
const fee_js_1 = require("./fee.js");
const resource_js_1 = require("./resource.js");
function createBaseGenesisState() {
    return { resources: [], feeParams: undefined };
}
exports.GenesisState = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        for (const v of message.resources) {
            resource_js_1.ResourceWithMetadata.encode(v, writer.uint32(10).fork()).join();
        }
        if (message.feeParams !== undefined) {
            fee_js_1.FeeParams.encode(message.feeParams, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGenesisState();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.resources.push(resource_js_1.ResourceWithMetadata.decode(reader, reader.uint32()));
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.feeParams = fee_js_1.FeeParams.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            resources: globalThis.Array.isArray(object?.resources)
                ? object.resources.map((e) => resource_js_1.ResourceWithMetadata.fromJSON(e))
                : [],
            feeParams: isSet(object.feeParams) ? fee_js_1.FeeParams.fromJSON(object.feeParams) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.resources?.length) {
            obj.resources = message.resources.map((e) => resource_js_1.ResourceWithMetadata.toJSON(e));
        }
        if (message.feeParams !== undefined) {
            obj.feeParams = fee_js_1.FeeParams.toJSON(message.feeParams);
        }
        return obj;
    },
    create(base) {
        return exports.GenesisState.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGenesisState();
        message.resources = object.resources?.map((e) => resource_js_1.ResourceWithMetadata.fromPartial(e)) || [];
        message.feeParams = (object.feeParams !== undefined && object.feeParams !== null)
            ? fee_js_1.FeeParams.fromPartial(object.feeParams)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=genesis.js.map