name: "Build & Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build Node.js"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: "Install buf CLI"
        uses: bufbuild/buf-setup-action@v1.27.2
        with:
          buf_user: ${{ secrets.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: "Clean install dependencies"
        run: npm ci

      - name: "Run npm build"
        run: npm run build
