name: "Build"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Check that works"
        run: "uname -a"

      - name: "Submodule update"
        run: "git submodule update"