name: Update ts-proto library
on:
  repository_dispatch:
    types: [protobuf_changes]
jobs:
  update-ts-proto:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.event.client_payload.taskID }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup buf.build
        uses: setup/buf.build

      - name: Generate TS code for protobufs
        run: buf generate buf.build/cheqd/cheqd-proto
      
      - name: Push to origin
        run: |
          git checkout -B ${{ env.BRANCH }}
          git add .
          git config --global user.name 'AutomationUser'
          git config --global user.email 'AutomationUser@users.noreply.github.com'
          git commit -am "chore(deps): Update protobufs"
          git push --force origin ${{ env.BRANCH }}

      - name: Create Pull Request
        run: gh pr create -B main -H ${{ ENV.BRANCH }} --title 'chore(deps)':' Update protobufs' --body 'Created by Github action' || true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
